export const FETCH_POSTS = "FETCH_POSTS"
export const ADD_POST = "ADD_POST"
export const DELETE_POST = "DELETE_POST"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const PUT_POST = "PUT_POST"
export const SET_VOTE_ID = "SELECT_VOTE_ID"
export const FETCH_CITY_WEATHER = "FETCH_CITY_WEATHER"
